apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:gEs8qnYlCAxqM/mfNXnmfp6fALq7cqCNqIsx3upJiEDlO3w50LWllj7PZjqlx2AqLzchX6Tao/hTvW2kXeAklqghJFeVlbqLcrpSKBjdMXy9m1mjio5+d2f+mJZCIJlXgNHUhd0Nm7SuMF1KPLDEJcDs2x2yz6BYy3AEnQhYS0kaPUD0DA5cgq/voHE6OEF3ZTleecK3OByHtU0x5nB63MWeLSI5apkpN1elFNgaTKRZ/NA5F1IjZy9go4t9xBBZnK1A7K0QgK/ylEzxoG6nxD7zS5+UQZDjxDC6tw4BtpC8L+UFJkARNVXlGwM=,iv:TwPzP82FH/zBVbwIsrov1cm8tDvfa7iyBa5JWwwt0mA=,tag:9F7s75F9qihRTz+QcuNV6w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1syd9u7d4ug786lmds0lekgmajzdpncheajcmdhanc7qw58tjhvwsgze9n8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5L1VlTldCYlk5eXdxNzJF
            dU9TUkVpK0h2UFBLSXRBZFRpVHBwN2hxYUNvCmYwVGF1K3NQcTJLWThTR01vMUxK
            TVJRdGVtRlhKbENqZUFjSEhjYnNKcE0KLS0tIFY1QS9tVnk1WDd2aXBWWmlUN3N5
            RXFNTnk1WTU3VEJxK2xQMWFJZUFmZzgKlAqZTGXxT8qAHhBE6JrMTe6MbjxyG2/S
            ksv5TSX17WZNpr3EVPikWHboErC1bGZC0x89mgwXBQDDyvSOm7kpcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T14:20:42Z"
    mac: ENC[AES256_GCM,data:M8IUqS70Gk2v6qIJmC3gCFSlHNmHjsRsix2ewp2jdb7/qS+6KZfUbEMf9+fxAl4lWevsJc2s1p/VGBcimfKoMVLNPLdIsqbQvFsKm9sgQZvGPF/JnFRV5nQFQkqNbAGP+gmAiL4VXf9Zj80A0rlsy2Sj0+K/8MPAqyhJjmEt4w8=,iv:POu3TWoXnsL4YWHXxxrcgLpO8SJoPQmr3hP+mHuGy8o=,tag:yRV+5BDKsfVsTY+RaM9gfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
