apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:gEs8qnYlCAxqM/mfNXnmfp6fALq7cqCNqIsx3upJiEDlO3w50LWllj7PZjqlx2AqLzchX6Tao/hTvW2kXeAklqghJFeVlbqLcrpSKBjdMXy9m1mjio5+d2f+mJZCIJlXgNHUhd0Nm7SuMF1KPLDEJcDs2x2yz6BYy3AEnQhYS0kaPUD0DA5cgq/voHE6OEF3ZTleecK3OByHtU0x5nB63MWeLSI5apkpN1elFNgaTKRZ/NA5F1IjZy9go4t9xBBZnK1A7K0QgK/ylEzxoG6nxD7zS5+UQZDjxDC6tw4BtpC8L+UFJkARNVXlGwM=,iv:TwPzP82FH/zBVbwIsrov1cm8tDvfa7iyBa5JWwwt0mA=,tag:9F7s75F9qihRTz+QcuNV6w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
    namespace: audiobookshelf
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1syd9v7d4ug786lmds0lekgmajzdpnche8jcmdhanc7qw58tjhvwsgze9n8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSLlV1LTldCYlk5eXdxNzJF
            dU9TUkVpk0h2UFBLSXRBZFRpVHBwN2hvYUNyCmYvGF1K3NQcTJLWThTR01vMUxK
            TVJRdGVtKthKbEtNQzQFjSEDjYnNKcEbKLs6t1FYiQS9tVnCiWDd2aXBNWmtUNsN5
            RXFNTnkiWTU3VEJxK2xQWWFJZUFmZzgKlAgZT0XxT8gAHhBEeJrMTe0Mbjxy02/S
            ksv5TSXi7WZNpr3EVPikWHboErC1b6ZC0x89mgwXBQDDyv50m7kpcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T14:20:42Z"
    mac: ENC[AES256_GCM,data:M8iUqS706kZv6qiJmCsgcFsiQNmHjsRslXz6wp2jdb7/qS+6KZfUbEHf9+fxKl4lWsvsJc2sip/VGBcimfKoHVLNPlaTsqDQyFsKm9sgQZv6PP/JnFRV5nQFQkqNbAGP+gmA1l4YXf9Zj80AOrisy2Sjo+k/0HPAqyhJ
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
